import type { House } from './types'

/** Les douze maisons : les domaines concrets de l'expérience (le « où »). */
export const HOUSES: House[] = [
  {
    id: 'maison-1', numero: 1, romain: 'I', nom: "L'Ascendant et le seuil",
    domaineTraditionnel: "Apparence, tempérament, manière d'arriver dans une situation, corps, premières impressions.",
    questionExistentielle: "Comment est-ce que j'apparais, et qui suis-je en train de devenir ?",
    archetype: "Le masque vivant, la porte d'entrée",
    psychologie: "La façon spontanée de se présenter, l'attitude par défaut face à la nouveauté.",
    ombre: "Se figer dans un rôle d'entrée ; confondre l'image de soi et soi.",
    potentiel: "Faire de son style une porte, pas un mur ; incarner ce qu'on devient.",
    planeteNaturelle: 'Mars', signeNaturel: 'Bélier',
    axe: 'I – VII', axeSens: "Moi / l'autre : s'affirmer et se relier.",
    exercice: "Demandez à trois personnes le premier mot qui leur vient sur vous. Comparez à l'image que vous croyez donner.",
    exempleInterpretation: "Une planète en Maison I colore fortement la première impression : Saturne y met de la réserve, Jupiter de la générosité apparente, la Lune une douceur mouvante.",
    categorie: 'angulaire',
  },
  {
    id: 'maison-2', numero: 2, romain: 'II', nom: "Les ressources",
    domaineTraditionnel: "Argent, biens, talents, corps comme ressource, ce à quoi on donne de la valeur.",
    questionExistentielle: "Qu'est-ce qui m'appartient vraiment, et qu'est-ce qui a de la valeur pour moi ?",
    archetype: "Le trésor, le jardin nourricier",
    psychologie: "L'estime de soi éprouvée à travers ce qu'on possède et ce qu'on sait faire.",
    ombre: "Confondre valeur personnelle et avoir ; accumuler par peur.",
    potentiel: "Fonder sa sécurité sur des talents cultivés et des valeurs choisies.",
    planeteNaturelle: 'Vénus', signeNaturel: 'Taureau',
    axe: 'II – VIII', axeSens: "Mes ressources / les ressources partagées ; avoir seul / échanger en profondeur.",
    exercice: "Listez cinq choses de valeur qui ne s'achètent pas et que vous possédez déjà.",
    exempleInterpretation: "Mars en Maison II peut indiquer une énergie mise à gagner sa vie, ou des tensions autour de l'argent et de l'autonomie matérielle.",
    categorie: 'succedente',
  },
  {
    id: 'maison-3', numero: 3, romain: 'III', nom: "L'environnement proche",
    domaineTraditionnel: "Fratrie, voisinage, apprentissages de base, déplacements courts, parole quotidienne.",
    questionExistentielle: "Comment est-ce que j'échange avec ce qui m'entoure directement ?",
    archetype: "Le carrefour, l'écolier",
    psychologie: "La façon d'apprendre, de nommer, de tisser des liens légers et fréquents.",
    ombre: "Rester en surface, se disperser, parler pour meubler.",
    potentiel: "Faire de la curiosité un art de relier ; devenir un passeur d'idées dans son milieu.",
    planeteNaturelle: 'Mercure', signeNaturel: 'Gémeaux',
    axe: 'III – IX', axeSens: "Le proche / le lointain ; savoir concret / vision d'ensemble.",
    exercice: "Pendant une journée, notez chaque question sincère que vous posez. Combien y en a-t-il ?",
    exempleInterpretation: "La Lune en Maison III : la sécurité passe par les échanges, l'écriture, le lien fraternel ; humeur sensible à l'ambiance des conversations.",
    categorie: 'cadente',
  },
  {
    id: 'maison-4', numero: 4, romain: 'IV', nom: "Les racines et le foyer",
    domaineTraditionnel: "Famille d'origine, maison, hérédité psychique, base intérieure, fin de vie.",
    questionExistentielle: "D'où est-ce que je viens, et sur quel socle intérieur est-ce que je me tiens ?",
    archetype: "La maison natale, la source",
    psychologie: "Le rapport à l'intime, au lignage, au sentiment d'avoir un lieu à soi.",
    ombre: "Rester prisonnier d'un roman familial ; chercher éternellement un foyer perdu.",
    potentiel: "Se donner une base intérieure stable ; réconcilier avec l'héritage.",
    planeteNaturelle: 'Lune', signeNaturel: 'Cancer',
    axe: 'IV – X', axeSens: "Le privé / le public ; les racines / la vocation.",
    exercice: "Dessinez le plan d'une maison qui vous représenterait. Quelle pièce est la plus grande ? Laquelle manque ?",
    exempleInterpretation: "Saturne en Maison IV : racines à construire par un travail patient ; sentiment ancien de sécurité à gagner plutôt que reçue.",
    categorie: 'angulaire',
  },
  {
    id: 'maison-5', numero: 5, romain: 'V', nom: "La création et le jeu",
    domaineTraditionnel: "Enfants, amours, art, plaisir, expression de soi, prise de risque joyeuse.",
    questionExistentielle: "Qu'est-ce que je mets au monde qui porte ma marque ?",
    archetype: "L'artiste, l'enfant qui joue, l'amoureux",
    psychologie: "Le besoin d'exister à travers ce qu'on crée et ce qu'on ose offrir.",
    ombre: "Créer pour l'applaudissement ; dramatiser ; fuir dans le jeu.",
    potentiel: "Créer pour la joie de créer ; laisser rayonner sa singularité.",
    planeteNaturelle: 'Soleil', signeNaturel: 'Lion',
    axe: 'V – XI', axeSens: "Ce que je crée seul / ce que nous portons ensemble.",
    exercice: "Faites une petite chose créative aujourd'hui sans la montrer. Qu'est-ce que l'acte, seul, vous a apporté ?",
    exempleInterpretation: "Vénus en Maison V : vie amoureuse et créative vive ; besoin de romantisme, de beauté, de jeu dans les liens.",
    categorie: 'succedente',
  },
  {
    id: 'maison-6', numero: 6, romain: 'VI', nom: "Le travail et le soin",
    domaineTraditionnel: "Travail quotidien, santé, hygiène de vie, service rendu, rapport au corps et aux routines.",
    questionExistentielle: "Comment est-ce que je me rends utile, et comment est-ce que je prends soin de mon instrument de vie ?",
    archetype: "L'artisan, le soignant",
    psychologie: "Le besoin de contribuer par un travail juste et d'ajuster son quotidien.",
    ombre: "Perfectionnisme anxieux ; se rendre indispensable ; négliger son corps.",
    potentiel: "Trouver la juste mesure de l'effort ; faire du quotidien une pratique.",
    planeteNaturelle: 'Mercure', signeNaturel: 'Vierge',
    axe: 'VI – XII', axeSens: "Le quotidien concret / la vie intérieure et l'invisible.",
    exercice: "Repérez une routine subie. Transformez-la en petit rituel conscient pendant une semaine.",
    exempleInterpretation: "Mars en Maison VI : beaucoup d'énergie mise dans le travail ; risque de surmenage ou de tensions avec les collègues.",
    categorie: 'cadente',
  },
  {
    id: 'maison-7', numero: 7, romain: 'VII', nom: "La relation",
    domaineTraditionnel: "Couple, associations, contrats, adversaires déclarés, le « toi » en face.",
    questionExistentielle: "Qui suis-je en face de l'autre, et qu'est-ce que l'autre me révèle ?",
    archetype: "Le partenaire, le miroir",
    psychologie: "L'apprentissage de l'altérité, du compromis, de l'engagement mutuel.",
    ombre: "Se perdre dans l'autre ; projeter sur le partenaire ce qu'on ne veut pas voir en soi.",
    potentiel: "Être en lien sans se dissoudre ; faire de la relation un lieu de conscience.",
    planeteNaturelle: 'Vénus', signeNaturel: 'Balance',
    axe: 'VII – I', axeSens: "L'autre / le moi.",
    exercice: "Notez trois reproches récurrents que vous faites à vos proches. En quoi vous parlent-ils de vous ?",
    exempleInterpretation: "Uranus en Maison VII : besoin de liberté dans les liens ; rencontres et ruptures imprévues ; attirance pour des partenaires atypiques.",
    categorie: 'angulaire',
  },
  {
    id: 'maison-8', numero: 8, romain: 'VIII', nom: "Les crises et les partages profonds",
    domaineTraditionnel: "Sexualité, mort, héritages, ressources de l'autre, transformations, ce qui est caché.",
    questionExistentielle: "Qu'est-ce que je suis prêt à perdre, et qu'est-ce que je partage vraiment en profondeur ?",
    archetype: "L'alchimiste, le passeur de seuils",
    psychologie: "Le rapport aux crises, à l'intimité qui engage, aux dettes et aux dons invisibles.",
    ombre: "Contrôle, fusion destructrice, refus de lâcher, fascination pour le pouvoir.",
    potentiel: "Traverser les morts symboliques ; se régénérer par la vérité partagée.",
    planeteNaturelle: 'Pluton', signeNaturel: 'Scorpion',
    axe: 'VIII – II', axeSens: "Ce qui se partage en profondeur / ce que je possède seul.",
    exercice: "Identifiez un attachement lié à un passé révolu. Quel petit geste de fin pourriez-vous poser ?",
    exempleInterpretation: "La Lune en Maison VIII : émotions intenses, besoin d'intimité totale, sensibilité aux non-dits familiaux ; transformations par les liens.",
    categorie: 'succedente',
  },
  {
    id: 'maison-9', numero: 9, romain: 'IX', nom: "Le sens et l'ailleurs",
    domaineTraditionnel: "Voyages lointains, études supérieures, philosophie, spiritualité, cultures étrangères, droit.",
    questionExistentielle: "Quel sens est-ce que je donne à mon expérience, et jusqu'où suis-je prêt à élargir mon horizon ?",
    archetype: "Le pèlerin, le professeur",
    psychologie: "Le besoin d'une vision, d'une foi, d'un cadre qui relie les faits à un sens.",
    ombre: "Dogmatisme ; fuir le concret dans les grands principes et les projets lointains.",
    potentiel: "Chercher le sens sans l'imposer ; incarner sa vision dans des actes.",
    planeteNaturelle: 'Jupiter', signeNaturel: 'Sagittaire',
    axe: 'IX – III', axeSens: "Le lointain et le sens / le proche et le concret.",
    exercice: "Écrivez en trois phrases votre « philosophie de vie » actuelle. Relisez-la dans un mois.",
    exempleInterpretation: "Mercure en Maison IX : l'esprit se nourrit de voyages, de lectures larges, de débats d'idées ; besoin d'apprendre en permanence.",
    categorie: 'cadente',
  },
  {
    id: 'maison-10', numero: 10, romain: 'X', nom: "La vocation et le rôle public",
    domaineTraditionnel: "Carrière, réputation, autorité, place dans la société, image publique, figure parentale structurante.",
    questionExistentielle: "Quelle est mon œuvre dans le monde, et de quoi est-ce que je veux répondre publiquement ?",
    archetype: "Le bâtisseur, la figure d'autorité",
    psychologie: "Le besoin d'accomplir quelque chose de visible et d'assumer une responsabilité.",
    ombre: "Réussir pour combler un manque de reconnaissance ancien ; se réduire à son statut.",
    potentiel: "Faire de sa vocation un service ; incarner une autorité juste.",
    planeteNaturelle: 'Saturne', signeNaturel: 'Capricorne',
    axe: 'X – IV', axeSens: "La vocation publique / les racines privées.",
    exercice: "Si votre travail n'existait plus demain, quelle contribution voudriez-vous quand même apporter au monde ?",
    exempleInterpretation: "Le Soleil en Maison X : besoin de se réaliser à travers une œuvre visible ; la question de la vocation est centrale dans la vie.",
    categorie: 'angulaire',
  },
  {
    id: 'maison-11', numero: 11, romain: 'XI', nom: "Les amitiés et les projets collectifs",
    domaineTraditionnel: "Amis, groupes, réseaux, idéaux, projets d'avenir, causes communes.",
    questionExistentielle: "Avec qui, et pour quel avenir, est-ce que je fais cause commune ?",
    archetype: "L'ami, le réformateur",
    psychologie: "Le besoin d'appartenir à une communauté choisie et de contribuer à un projet plus grand que soi.",
    ombre: "Se fondre dans le groupe ; militer pour l'humanité abstraite en négligeant les proches.",
    potentiel: "Être singulier et solidaire ; mettre son originalité au service du collectif.",
    planeteNaturelle: 'Uranus', signeNaturel: 'Verseau',
    axe: 'XI – V', axeSens: "Le nous et l'avenir / le je et la création personnelle.",
    exercice: "Nommez le projet collectif qui vous tient le plus à cœur. Quel est votre prochain petit pas concret pour lui ?",
    exempleInterpretation: "Jupiter en Maison XI : les amitiés et les réseaux ouvrent des opportunités ; goût des projets à visée large.",
    categorie: 'succedente',
  },
  {
    id: 'maison-12', numero: 12, romain: 'XII', nom: "L'invisible et le retrait",
    domaineTraditionnel: "Inconscient, solitude, épreuves cachées, lieux de retrait, héritage transgénérationnel, vie intérieure.",
    questionExistentielle: "Qu'est-ce qui agit en moi à mon insu, et à quoi suis-je relié au-delà de mon petit moi ?",
    archetype: "Le mystique, l'ermite, le rêveur",
    psychologie: "Le rapport à ce qui échappe au contrôle : rêves, peurs anciennes, élan spirituel, don de soi.",
    ombre: "Se saboter dans l'ombre ; fuir le monde ; se noyer dans le flou ou le sacrifice.",
    potentiel: "Faire du retrait une source ; laisser passer à travers soi compassion, art, sens.",
    planeteNaturelle: 'Neptune', signeNaturel: 'Poissons',
    axe: 'XII – VI', axeSens: "L'invisible et l'intérieur / le quotidien concret.",
    exercice: "Tenez un carnet de rêves une semaine. Notez seulement les images fortes, sans les interpréter d'abord.",
    exempleInterpretation: "Le Soleil en Maison XII : identité discrète, vie intérieure riche ; la réalisation passe souvent par un travail dans l'ombre ou d'aide aux autres.",
    categorie: 'cadente',
  },
]

export const HOUSE_BY_NUM = Object.fromEntries(HOUSES.map((h) => [h.numero, h])) as Record<number, House>
