import type { Planet } from './types'

/** Les planètes comme fonctions psychologiques / archétypes. Contenu original. */
export const PLANETS: Planet[] = [
  {
    id: 'soleil',
    nom: 'Soleil',
    glyphe: '☉',
    categorie: 'luminaire',
    fonction: "Fonction d'identité et de rayonnement : ce qui, en nous, cherche à devenir soi et à briller.",
    archetype: "Le roi / l'enfant royal, le héros, le centre",
    principe: "Individuation, volonté consciente, direction de vie.",
    expressionHarmonieuse: "Confiance tranquille, générosité, capacité à créer, à décider, à assumer une direction ; on rayonne sans écraser.",
    expressionDesequilibree: "Orgueil ou, à l'inverse, effacement ; besoin d'admiration, difficulté à trouver sa place, à dire « je veux ».",
    ombre: "L'ego qui exige d'être le centre, ou l'identité empruntée à un père, un modèle, un rôle.",
    potentielEvolutif: "Passer de l'ego qui réclame de la lumière au Soi qui en donne : devenir un foyer pour les autres.",
    questionInitiatique: "Qu'est-ce qui cherche à rayonner à travers moi, et qu'est-ce que je fais pour l'en empêcher ?",
    mythologie: "Figures des dieux solaires traversant le ciel (Hélios, Apollon dans son versant lumineux, Râ).",
    jung: "Le Soi comme centre organisateur de la psyché, distinct de l'ego ; le processus d'individuation.",
    tarot: "Rapproché de l'arcane du Soleil (joie, clarté, vitalité). Correspondance moderne, non universelle.",
    alchimie: "L'or philosophal, principe fixe et parfait ; le but rayonnant de l'Œuvre.",
    hermetisme: "Principe de Vibration : le centre qui irradie et met tout le reste en mouvement.",
    exemplesTheme: [
      "Soleil en Lion : l'identité se cherche dans la création et la reconnaissance chaleureuse.",
      "Soleil en Verseau : l'identité se construit dans la différence assumée et l'appartenance à un idéal.",
      "Soleil en Maison X : le besoin de se réaliser passe par l'œuvre publique et la vocation.",
    ],
    correspondances: [
      { domaine: 'Jung', contenu: "Axe ego–Soi.", tag: 'rapprochement-moderne' },
      { domaine: 'Tarot', contenu: "Le Soleil (XIX).", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'lune',
    nom: 'Lune',
    glyphe: '☽',
    categorie: 'luminaire',
    fonction: "Fonction de sensibilité et de besoin : ce qui, en nous, ressent, se souvient, cherche à être nourri et rassuré.",
    archetype: "La mère, l'enfant intérieur, la nourrice",
    principe: "Vie affective, mémoire, réactions instinctives, monde de l'enfance.",
    expressionHarmonieuse: "Sécurité intérieure, capacité à ressentir et à réconforter, intuition juste des besoins, imagination fertile.",
    expressionDesequilibree: "Hypersensibilité, dépendance affective, humeurs changeantes, repli, besoin de contrôle par le soin.",
    ombre: "Les schémas affectifs hérités de l'enfance, rejoués sans le savoir ; la peur d'être abandonné.",
    potentielEvolutif: "Devenir sa propre mère : se donner la sécurité que l'on attendait de l'extérieur.",
    questionInitiatique: "De quoi ai-je besoin pour me sentir en sécurité — et est-ce que je me le donne ?",
    mythologie: "Déesses lunaires et maternelles (Séléné, Artémis, Déméter dans son versant nourricier).",
    jung: "Archétype de la Mère ; rapport au monde matriciel et à l'inconscient personnel de l'enfance.",
    tarot: "Rapproché de l'arcane de la Lune (imaginaire, nuit, inconscient). Correspondance moderne.",
    alchimie: "L'argent, principe réceptif et changeant ; l'eau qui reçoit et reflète.",
    hermetisme: "Principe de Rythme : les phases, les marées de l'humeur, l'alternance des états.",
    exemplesTheme: [
      "Lune en Cancer : besoin fort de foyer, de racines, de liens familiaux ; grande porosité émotionnelle.",
      "Lune en Capricorne : besoin de se sentir utile et solide ; pudeur, difficulté à demander du réconfort.",
      "Lune en Maison III : la sécurité passe par les mots, les échanges, le lien fraternel.",
    ],
    correspondances: [
      { domaine: 'Jung', contenu: "Archétype de la Mère.", tag: 'rapprochement-moderne' },
      { domaine: 'Tarot', contenu: "La Lune (XVIII).", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'mercure',
    nom: 'Mercure',
    glyphe: '☿',
    categorie: 'personnelle',
    fonction: "Fonction mentale : percevoir, nommer, relier, apprendre, communiquer.",
    archetype: "Le messager, l'écolier, le passeur",
    principe: "Intelligence, langage, circulation des idées, adaptation.",
    expressionHarmonieuse: "Curiosité, clarté d'expression, agilité mentale, capacité à relier des domaines, humour.",
    expressionDesequilibree: "Dispersion, bavardage, rationalisation, anxiété mentale, difficulté à se concentrer ou à écouter.",
    ombre: "Le mental qui se met au service de la fuite : parler pour ne pas ressentir, argumenter pour ne pas changer.",
    potentielEvolutif: "Mettre l'intelligence au service de la conscience : penser pour comprendre, pas seulement pour avoir raison.",
    questionInitiatique: "Est-ce que je pense, ou est-ce que je répète ?",
    mythologie: "Hermès / Mercure, messager des dieux, guide des âmes, dieu des voyageurs et des marchands.",
    jung: "Figure du trickster et fonction de médiation entre conscient et inconscient.",
    tarot: "Rapproché du Bateleur / Magicien (habileté, parole, outils). Correspondance moderne.",
    alchimie: "Le Mercure des philosophes, esprit volatil et médiateur ; l'agent des transformations.",
    hermetisme: "Principe de Mentalisme : nommer et penser, c'est déjà façonner l'expérience.",
    exemplesTheme: [
      "Mercure en Gémeaux : pensée rapide, curieuse, associative ; besoin de varier les sujets.",
      "Mercure en Poissons : pensée imagée, intuitive, poétique ; logique moins linéaire.",
      "Mercure en Maison IX : l'esprit se nourrit de voyages, de philosophie, d'apprentissages larges.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Hermès / Mercure.", tag: 'traditionnel' },
      { domaine: 'Tarot', contenu: "Le Bateleur (I).", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'venus',
    nom: 'Vénus',
    glyphe: '♀',
    categorie: 'personnelle',
    fonction: "Fonction de valeur et de lien : ce qui attire, ce qu'on aime, ce qu'on trouve beau et désirable.",
    archetype: "L'amante, l'artiste, la médiatrice",
    principe: "Amour, plaisir, harmonie, sens esthétique, rapport à la valeur.",
    expressionHarmonieuse: "Capacité d'aimer et de recevoir, goût, sens de l'accord et de la beauté, diplomatie, plaisir sain.",
    expressionDesequilibree: "Dépendance à l'approbation, séduction compulsive, complaisance, superficialité, difficulté à choisir.",
    ombre: "Se rendre aimable au prix de soi ; confondre être aimé et avoir de la valeur.",
    potentielEvolutif: "Aimer depuis un centre : choisir ses liens, connaître sa propre valeur sans la mendier.",
    questionInitiatique: "Qu'est-ce qui a vraiment de la valeur pour moi, indépendamment du regard des autres ?",
    mythologie: "Aphrodite / Vénus, née de l'écume ; déesse de l'amour, du désir et des accords.",
    jung: "Aspect de l'anima ; fonction du sentiment (évaluer, aimer, donner du prix).",
    tarot: "Rapproché de l'Impératrice (fécondité, beauté) ou des Amoureux. Correspondance moderne.",
    alchimie: "Le cuivre ; l'union des principes, la conjonction harmonieuse.",
    hermetisme: "Principe de Polarité : l'attraction qui relie les contraires.",
    exemplesTheme: [
      "Vénus en Taureau : amour sensuel, fidèle, lent ; besoin de sécurité et de plaisir concret.",
      "Vénus en Verseau : amour qui a besoin de liberté et d'amitié ; se méfie de la fusion.",
      "Vénus en Maison VII : la vie affective et les partenariats sont un lieu central d'apprentissage.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Aphrodite / Vénus.", tag: 'traditionnel' },
      { domaine: 'Jung', contenu: "Fonction sentiment.", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'mars',
    nom: 'Mars',
    glyphe: '♂',
    categorie: 'personnelle',
    fonction: "Fonction d'affirmation et d'action : la capacité de vouloir, de décider, d'aller vers ce qu'on désire, de se défendre.",
    archetype: "Le guerrier, le pionnier, le chasseur",
    principe: "Volonté, désir, courage, énergie de conquête et de séparation.",
    expressionHarmonieuse: "Courage, décision, capacité d'agir et de dire non, énergie disponible, franchise.",
    expressionDesequilibree: "Colère, violence, impulsivité — ou inhibition, passivité, difficulté à s'affirmer et à désirer.",
    ombre: "La force retournée contre soi (auto-sabotage) ou déchargée sur autrui ; la guerre pour se sentir vivant.",
    potentielEvolutif: "Passer de la réaction à l'action choisie : mettre sa force au service d'une intention claire.",
    questionInitiatique: "Comment est-ce que j'utilise ma force ?",
    mythologie: "Arès / Mars, dieu de la guerre ; dans le versant grec, la fureur brute ; dans le versant romain, la puissance qui protège la cité.",
    jung: "Fonction de confrontation et d'affirmation ; énergie nécessaire à la différenciation du moi.",
    tarot: "Rapproché de la Tour (rupture, décharge) ou de l'Empereur dans son versant combatif. Correspondance moderne.",
    alchimie: "Le fer ; le feu qui sépare, la calcination.",
    hermetisme: "Principe de Vibration : l'énergie qui se met en mouvement et rompt l'inertie.",
    exemplesTheme: [
      "Mars en Bélier : action directe, rapide, franche ; impatience, goût du défi.",
      "Mars en Cancer : l'affirmation passe par la protection des siens ; colère plus indirecte, par vagues.",
      "Mars en Maison X : l'énergie se déploie dans l'ambition, la carrière, la conquête d'une place.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Arès / Mars.", tag: 'traditionnel' },
      { domaine: 'Jung', contenu: "Fonction de confrontation.", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'jupiter',
    nom: 'Jupiter',
    glyphe: '♃',
    categorie: 'sociale',
    fonction: "Fonction d'expansion et de sens : ce qui, en nous, cherche à grandir, à comprendre, à faire confiance à la vie.",
    archetype: "Le sage, le guide, le bienfaiteur",
    principe: "Croissance, foi, sens, générosité, vision d'ensemble.",
    expressionHarmonieuse: "Optimisme fondé, générosité, sens de l'opportunité, capacité à donner du sens et à inspirer confiance.",
    expressionDesequilibree: "Excès, exagération, promesses non tenues, dogmatisme, fuite en avant, prétention à savoir.",
    ombre: "Le « toujours plus » qui masque un vide ; la vérité proclamée pour ne pas la vivre.",
    potentielEvolutif: "Passer de l'expansion quantitative à la croissance de conscience : grandir en profondeur.",
    questionInitiatique: "Vers quoi est-ce que je grandis — et est-ce que cette croissance a un sens pour moi ?",
    mythologie: "Zeus / Jupiter, roi des dieux, garant de l'ordre, du droit et de l'hospitalité.",
    jung: "Fonction d'amplification du sens ; rapport à l'image du guide intérieur.",
    tarot: "Rapproché de la Roue de Fortune (cycles, chance) ou du Pape (sens, transmission). Correspondance moderne.",
    alchimie: "L'étain ; la dilatation, la mise en circulation.",
    hermetisme: "Principe de Correspondance : relier le particulier au général, le bas au haut.",
    exemplesTheme: [
      "Jupiter en Sagittaire : besoin d'horizons larges, de voyages, de philosophie, de liberté de croire.",
      "Jupiter en Vierge : la croissance passe par le perfectionnement d'un savoir-faire utile.",
      "Jupiter en Maison II : tendance à voir grand en matière de ressources ; leçon sur la juste mesure.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Zeus / Jupiter.", tag: 'traditionnel' },
      { domaine: 'Hermétisme', contenu: "Principe de Correspondance.", tag: 'interpretation-symbolique' },
    ],
  },
  {
    id: 'saturne',
    nom: 'Saturne',
    glyphe: '♄',
    categorie: 'sociale',
    fonction: "Fonction de structure et de limite : ce qui, en nous, construit, cadre, exige, et confronte au temps et au réel.",
    archetype: "Le vieux sage, le gardien du seuil, le maître exigeant",
    principe: "Responsabilité, maturité, concentration, épreuve, durée.",
    expressionHarmonieuse: "Rigueur, patience, sens des responsabilités, capacité à durer, autorité intérieure, sobriété.",
    expressionDesequilibree: "Peur, rigidité, pessimisme, culpabilité, dureté envers soi et autrui, sentiment d'insuffisance.",
    ombre: "Le juge intérieur qui condamne d'avance ; la peur déguisée en réalisme.",
    potentielEvolutif: "Transformer la contrainte subie en discipline choisie : Saturne devient alors un allié, pas un geôlier.",
    questionInitiatique: "Quelle peur suis-je en train d'appeler « réalisme » ?",
    mythologie: "Cronos / Saturne, dieu du temps qui dévore ses enfants ; figure de la limite et de la loi ancienne.",
    jung: "Le Senex (le vieux) ; rapport au surmoi, à l'autorité, à la loi intériorisée.",
    tarot: "Rapproché du Monde (achèvement, structure) ou de l'Ermite (rigueur, solitude). Correspondance moderne.",
    alchimie: "Le plomb, matière la plus lourde à transmuter ; le nigredo saturnien, l'épreuve initiale.",
    hermetisme: "Principe de Cause et effet : on récolte dans le temps ce que l'on a semé.",
    exemplesTheme: [
      "Saturne en Capricorne : forte exigence de réussite structurée ; leçon sur la valeur intrinsèque au-delà du statut.",
      "Saturne en Balance : apprentissage lent et sérieux de la relation, de l'engagement, du juste échange.",
      "Saturne en Maison IV : sécurité et racines à construire par un travail intérieur patient.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Cronos / Saturne.", tag: 'traditionnel' },
      { domaine: 'Jung', contenu: "Le Senex.", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'uranus',
    nom: 'Uranus',
    glyphe: '♅',
    categorie: 'transpersonnelle',
    fonction: "Fonction de libération et d'éveil : ce qui rompt les cadres devenus trop étroits et ouvre à l'inattendu.",
    archetype: "Le révolutionnaire, l'éclair, le prométhéen",
    principe: "Individuation radicale, rupture, innovation, liberté.",
    expressionHarmonieuse: "Originalité, lucidité soudaine, capacité à se réinventer, à penser hors du cadre, à libérer.",
    expressionDesequilibree: "Instabilité, rébellion réflexe, coupures brutales, froideur, fuite de tout engagement.",
    ombre: "La rupture comme défense contre l'intimité ; se croire au-dessus des lois communes.",
    potentielEvolutif: "Distinguer la vraie liberté (choix conscient) de la simple réaction contre.",
    questionInitiatique: "Qu'est-ce qui, en moi, demande à être libéré — et qu'est-ce que je fuis en cassant tout ?",
    mythologie: "Prométhée, voleur de feu, qui transgresse l'ordre divin pour faire avancer l'humanité.",
    jung: "L'irruption de l'inconscient qui bouscule les structures du moi ; fonction de renouvellement.",
    tarot: "Rapproché de la Tour (foudre, effondrement libérateur) ou du Mat. Correspondance moderne.",
    alchimie: "L'éclair qui fend le vase, la fulguration qui libère l'esprit prisonnier de la matière.",
    hermetisme: "Principe de Rythme dans sa phase de renversement : le balancier qui repart en sens inverse.",
    exemplesTheme: [
      "Uranus en Maison VII : besoin de liberté dans les liens ; ruptures et rencontres imprévues.",
      "Uranus en aspect au Soleil : identité marquée par le besoin d'être différent et libre.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Prométhée.", tag: 'rapprochement-moderne' },
      { domaine: 'Tarot', contenu: "La Maison Dieu / La Tour (XVI).", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'neptune',
    nom: 'Neptune',
    glyphe: '♆',
    categorie: 'transpersonnelle',
    fonction: "Fonction de dissolution et de reliance : ce qui efface les frontières du moi pour ouvrir au rêve, à la compassion, au sacré.",
    archetype: "Le mystique, le rêveur, l'artiste inspiré",
    principe: "Idéal, imaginaire, unité, sacrifice, transcendance.",
    expressionHarmonieuse: "Compassion, inspiration créatrice, foi, sensibilité au beau et à l'invisible, capacité de pardon.",
    expressionDesequilibree: "Illusion, confusion, addictions, fuite, idéalisation, rôles de victime ou de sauveur.",
    ombre: "Le brouillard confortable qui dispense de choisir et de voir les choses en face.",
    potentielEvolutif: "Passer de la fuite hors du réel à la traversée du réel avec plus de compassion et de sens.",
    questionInitiatique: "Où est-ce que je préfère le rêve d'une chose à la chose elle-même ?",
    mythologie: "Poséidon / Neptune, dieu de l'océan et des profondeurs mouvantes ; les figures qui se sacrifient pour relier les mondes.",
    jung: "Rapport à l'océan de l'inconscient collectif ; expérience du numineux et risque d'inflation.",
    tarot: "Rapproché de la Lune (illusions, inconscient) ou du Pendu (abandon, autre regard). Correspondance moderne.",
    alchimie: "La dissolution (solve), l'eau qui défait toutes les formes.",
    hermetisme: "Principe de Mentalisme : tout est relié dans un même champ ; les séparations sont relatives.",
    exemplesTheme: [
      "Neptune en Maison X : vocation floue ou idéaliste ; leçon sur l'ancrage concret d'un rêve.",
      "Neptune en aspect à Vénus : amour teinté d'idéal ; risque d'idéalisation, don de tendresse universelle.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Poséidon / Neptune.", tag: 'rapprochement-moderne' },
      { domaine: 'Alchimie', contenu: "Solve.", tag: 'interpretation-symbolique' },
    ],
  },
  {
    id: 'pluton',
    nom: 'Pluton',
    glyphe: '♇',
    categorie: 'transpersonnelle',
    fonction: "Fonction de transformation : ce qui, en nous, détruit ce qui doit mourir et régénère en profondeur.",
    archetype: "L'alchimiste, le maître du seuil, le phénix",
    principe: "Puissance, crise, mort et renaissance, mise à nu.",
    expressionHarmonieuse: "Lucidité radicale, courage de la vérité, capacité de régénération, présence dans les passages difficiles.",
    expressionDesequilibree: "Contrôle, manipulation, obsession, destruction, fascination pour le pouvoir ou la fin.",
    ombre: "Le refus de perdre : retenir, contrôler, détruire plutôt que lâcher.",
    potentielEvolutif: "Accepter les morts symboliques nécessaires ; utiliser la puissance pour transformer, non pour dominer.",
    questionInitiatique: "Qu'est-ce qui doit mourir en moi pour que quelque chose de vrai puisse naître ?",
    mythologie: "Hadès / Pluton, maître du monde souterrain et des richesses cachées ; le rapt de Perséphone et le cycle des saisons.",
    jung: "Travail avec l'Ombre et les contenus les plus refoulés ; la mort-renaissance de l'individuation.",
    tarot: "Rapproché de la Mort (XIII) et parfois du Jugement (résurrection). Correspondance moderne.",
    alchimie: "Le nigredo, l'œuvre au noir ; la putréfaction qui précède toute renaissance.",
    hermetisme: "Principe de Genre : toute création nouvelle passe par une gestation obscure.",
    exemplesTheme: [
      "Pluton en Maison VIII : rapport intense aux crises, à l'intimité profonde, aux transmissions.",
      "Pluton en aspect à la Lune : émotions puissantes, enjeux de contrôle affectif, transformations par les liens.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Hadès / Pluton ; Perséphone.", tag: 'rapprochement-moderne' },
      { domaine: 'Alchimie', contenu: "Nigredo.", tag: 'interpretation-symbolique' },
    ],
  },
  {
    id: 'chiron',
    nom: 'Chiron',
    glyphe: '⚷',
    categorie: 'point',
    fonction: "Point sensible : la blessure qui ne guérit pas tout à fait, et qui devient source de soin pour les autres.",
    archetype: "Le guérisseur blessé, le maître initiateur",
    principe: "Blessure, transmission, art de faire de sa faille une ressource.",
    expressionHarmonieuse: "Compassion lucide, capacité d'accompagner, transmission d'un savoir né de l'épreuve.",
    expressionDesequilibree: "Identification à la blessure, rôle de victime, ou déni total de la faille.",
    ombre: "Se définir par sa souffrance, ou soigner les autres pour ne pas se regarder.",
    potentielEvolutif: "Cesser d'attendre une guérison parfaite ; transformer la faille en pont vers autrui.",
    questionInitiatique: "Que puis-je transmettre précisément parce que j'ai traversé cette blessure ?",
    mythologie: "Chiron, le centaure blessé par une flèche empoisonnée, incapable de se guérir mais devenu maître des héros.",
    jung: "Figure du guérisseur blessé (wounded healer) ; l'accès au soin par la reconnaissance de sa propre plaie.",
    tarot: "Rapproché parfois de l'Ermite (sagesse née de l'épreuve). Correspondance moderne, discutée.",
    alchimie: "Le remède tiré du poison même : la teinture obtenue par le travail sur la matière malade.",
    hermetisme: "Principe de Polarité : la blessure et le don sont les deux faces d'un même point.",
    exemplesTheme: [
      "Chiron en Maison I : sentiment ancien de ne pas être à sa place ; don, avec le temps, d'aider les autres à trouver la leur.",
    ],
    correspondances: [
      { domaine: 'Mythe', contenu: "Chiron.", tag: 'traditionnel' },
      { domaine: 'Jung', contenu: "Le guérisseur blessé.", tag: 'rapprochement-moderne' },
    ],
  },
  {
    id: 'noeud-nord',
    nom: 'Nœud Nord',
    glyphe: '☊',
    categorie: 'point',
    fonction: "Direction de croissance : le type d'expérience vers lequel il est fécond d'apprendre à aller, même si c'est inconfortable.",
    archetype: "Le cap, l'appel, la marche à gravir",
    principe: "Axe d'évolution ; ce qui n'est pas encore acquis et demande à être développé.",
    expressionHarmonieuse: "Acceptation d'un apprentissage neuf ; sortie progressive de la zone de confort.",
    expressionDesequilibree: "Refus, retour systématique aux vieux réflexes (pôle du Nœud Sud), sentiment de tourner en rond.",
    ombre: "Prendre le confort du connu (Nœud Sud) pour sa vraie nature.",
    potentielEvolutif: "Faire du Nœud Nord une boussole : dans le doute, choisir la direction qu'il indique.",
    questionInitiatique: "Quelle expérience est-ce que j'évite systématiquement alors qu'elle me ferait grandir ?",
    mythologie: "Les points où la route de la Lune croise celle du Soleil : symboliquement, le lieu de rencontre entre le connu et l'inconnu.",
    jung: "Orientation du processus d'individuation ; le pas suivant vers la totalité.",
    tarot: "Rapproché du Mat en marche (le voyage à venir). Correspondance moderne.",
    alchimie: "La direction de l'Œuvre, l'intention qui oriente les opérations.",
    hermetisme: "Principe de Rythme : après une longue oscillation d'un côté, apprendre l'autre mouvement.",
    exemplesTheme: [
      "Nœud Nord en Maison VII : apprendre la relation et la coopération, après une longue habitude d'autonomie (Nœud Sud en I).",
    ],
    correspondances: [
      { domaine: 'Astronomie', contenu: "Nœud lunaire ascendant (point orbital, pas un corps).", tag: 'traditionnel' },
    ],
  },
  {
    id: 'lune-noire',
    nom: 'Lune Noire (Lilith)',
    glyphe: '⚸',
    categorie: 'point',
    fonction: "Point sensible : le lieu d'un refus intérieur, d'une exigence non négociable, d'une part sauvage qui ne veut pas se soumettre.",
    archetype: "La rebelle, l'exilée, la part indomptée",
    principe: "Refus, manque fondateur, intégrité farouche.",
    expressionHarmonieuse: "Fidélité à une vérité intime ; capacité à dire un « non » juste et fondateur.",
    expressionDesequilibree: "Sabotage, provocation, rejet de tout cadre, blessure rejouée comme fatalité.",
    ombre: "Le refus par principe qui isole ; l'orgueil de la marge.",
    potentielEvolutif: "Écouter ce que le refus protège de précieux, et le mettre au service de la vie plutôt que du repli.",
    questionInitiatique: "À quoi est-ce que je refuse absolument de me plier — et qu'est-ce que ce refus garde de sacré ?",
    mythologie: "Les figures de la première femme qui refuse la soumission et choisit l'exil plutôt que l'inégalité (traditions diverses).",
    jung: "Aspect de l'Ombre au féminin ; la part refoulée par les normes collectives.",
    tarot: "Rapproché parfois de la Lune dans son versant nocturne et sauvage. Correspondance moderne, discutée.",
    alchimie: "La materia prima rejetée, la « pierre que les bâtisseurs ont écartée ».",
    hermetisme: "Principe de Polarité : le pôle nié qui, non reconnu, gouverne en secret.",
    exemplesTheme: [
      "Lune Noire en Maison IV : rapport complexe aux racines ; besoin de rompre avec un héritage familial pour exister.",
    ],
    correspondances: [
      { domaine: 'Astronomie', contenu: "Selon la définition : foyer vide de l'orbite lunaire (Lune Noire moyenne).", tag: 'traditionnel' },
      { domaine: 'Jung', contenu: "Ombre au féminin.", tag: 'rapprochement-moderne' },
    ],
  },
]

export const PLANET_BY_ID = Object.fromEntries(PLANETS.map((p) => [p.id, p])) as Record<string, Planet>
